### ISSUE TITLE
Default number of threads for ASIO io_service.

### ISSUE THREAD

**Issue by jade2k11598** [Microsoft/cpprestsdk#704] opened 2018-02-21 19:47 UTC
Hi, 
I wasn't sure where to post this (there wasn't really a forum on this particular github to ask questions), but I was following the simple example of setting up an [http client in the tutorial](https://github.com/microsoft/cpprestsdk/wiki/Getting-Started-Tutorial).  I literally copied and pasted the code and built it and ran it and I notice that when this simple application runs, it spawns 43-45 threads.  I understand that it uses the boost::asio for its asynchronous IO.  I took a stack trace of the application when it ran and it had about 42 threads dedicated to boost::asio::io_service::run().  Why is the number of threads for the thread pool used for boost asio that high by default?  In most cases (and particularly in this simple case), the number of threads spawn is std::thread::hardware_concurrency() (C++11).  For my case, my hardware_concurrency returns 8.  It just seems rather wasteful resources to be spawning that many threads by default.

Is there a way to control how many threads should be used by the boost asio io_service when using this REST SDK?  Also does one have access to the io_service used by this REST SDK?  I'd like to have the ability to post other handlers (not necessarily serially as the "then" function provides).  I could create my own io_service, but I find that wasteful when there's already an io_service that the REST SDK is using.

**Comment by garethsb-sony** [comment] 2018-02-22 07:26
One of the biggest issues around this is that the use of ASIO or not to implement pplx::task scheduler and http_listener depends on platform and various preprocessor definitions. See also discussion in #241, #428, #441 and e.g. 9da20abfac1facb68752e52c3c69ff41506a2f1f which has recently been merged to master.

**Comment by vadz** [comment] 2018-05-09 00:07
I'd just like to add that replacing hardcoded 40 with 10 in `src/pplx/threadpool.cpp` results in an immediate crash, even with just a single network operation, inside `async_resolve()`, at least under macOS. I have no idea what's going on here, but it seems very suspicious that lowering the number of threads (to a value still clearly above what's needed) results in this...

**Comment by mobileben** [comment] 2018-06-06 05:20
I actually have a new pull request for this. The last one was never accepted as it has a conflict.

https://github.com/Microsoft/cpprestsdk/pull/775

BTW @vadz I set it to 10, and it doesn't have an issue. I'm running on both MacOS and iOS.

**Comment by vadz** [comment] 2018-06-06 11:53
Thanks for the link to the PR!

As for the crash with 10 threads, it might have been a red herring, sorry. I was trying several things at the same time and maybe it was due to something I did. I'll try to reproduce it again, using #775, when I test under Mac the next time.

**Comment by BillyONeal** [comment] 2018-10-18 07:33
API to change this added in https://github.com/Microsoft/cpprestsdk/pull/883

**Closed by BillyONeal** 2018-10-18 07:33 UTC
