### ISSUE TITLE
/usr/bin/ld: cannot find -lpthreads

### ISSUE THREAD

**Issue by waas1919** [Microsoft/cpprestsdk#600] opened 2017-11-09 12:07 UTC
I've following the steps as the `wiki `says:

```
sudo apt-get install g++ git make zlib1g-dev libboost-all-dev libssl-dev cmake
git clone https://github.com/Microsoft/cpprestsdk.git casablanca
cd casablanca/Release
mkdir build.debug
cd build.debug
cmake .. -DCMAKE_BUILD_TYPE=Debug
```

On this step `cmake .. -DCMAKE_BUILD_TYPE=Debug` I get the following error: `-- Looking for pthread_create - not found` as seen below.

```
root@ubuntu:~/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug# cmake .. -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Setting gcc options
CMake Error at src/CMakeLists.txt:14 (list):
  list does not recognize sub-command FILTER


-- Found websocketpp version 0.7.0 on system
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   random
--   system
--   thread
--   filesystem
--   chrono
--   atomic
--   date_time
--   regex
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.2g", minimum required is "1.0.0") 
-- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE
-- Performing Test _SSL_LEAK_SUPPRESS_AVAILABLE - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Added test library httpclient_test
-- Added test library httplistener_test
-- Added test library json_test
-- Added test library pplx_test
-- Added test library streams_test
-- Added test library uri_test
-- Added test library utils_test
-- Added test library websocketsclient_test
-- Configuring incomplete, errors occurred!
See also "/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeOutput.log".
See also "/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeError.log".
```

And looking at the `CMakeError.log` I see the following error: `/usr/bin/ld: cannot find -lpthreads` as seen below.

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f6c64/fast"
/usr/bin/make -f CMakeFiles/cmTC_f6c64.dir/build.make CMakeFiles/cmTC_f6c64.dir/build
make[1]: Entering directory '/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f6c64.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_f6c64.dir/CheckSymbolExists.c.o   -c /home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_f6c64
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f6c64.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_f6c64.dir/CheckSymbolExists.c.o  -o cmTC_f6c64 -rdynamic 
CMakeFiles/cmTC_f6c64.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_f6c64.dir/build.make:97: recipe for target 'cmTC_f6c64' failed
make[1]: *** [cmTC_f6c64] Error 1
make[1]: Leaving directory '/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_f6c64/fast' failed
make: *** [cmTC_f6c64/fast] Error 2

File /home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b723a/fast"
/usr/bin/make -f CMakeFiles/cmTC_b723a.dir/build.make CMakeFiles/cmTC_b723a.dir/build
make[1]: Entering directory '/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b723a.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_b723a.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_b723a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b723a.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_b723a.dir/CheckFunctionExists.c.o  -o cmTC_b723a -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_b723a.dir/build.make:97: recipe for target 'cmTC_b723a' failed
make[1]: *** [cmTC_b723a] Error 1
make[1]: Leaving directory '/home/hhh/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_b723a/fast' failed
make: *** [cmTC_b723a/fast] Error 2
```

I understand that the `pthread `lib should be on the `/usr/bin/ld`, as it says the error:
`/usr/bin/ld: cannot find -lpthreads`

But, mine is on the `/lib/x86_64-linux-gnu`:

```
root@ubuntu:~/hhh/workspace/projs/CppRestSdk/casablanca/Release/build.debug# ldconfig -p | grep pthread
	libpthread.so.0 (libc6,x86-64, OS ABI: Linux 2.6.32) => /lib/x86_64-linux-gnu/libpthread.so.0
	libpthread.so.0 (libc6, OS ABI: Linux 2.6.32) => /lib/i386-linux-gnu/libpthread.so.0
	libgpgme-pthread.so.11 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgpgme-pthread.so.11
```

How can I compile using cmake, but setting the pthread lib on the correct location?

I know that for `g++ -lpthread` must be set, but to generate the `libcpprestsdk.a` how can I achieve this?

Many thanks!:)

**Comment by waas1919** [comment] 2017-11-09 12:20
After seeing this thread `https://github.com/caffe2/caffe2/issues/1234` I've also tried their solution, which would be for this case:

`git clone --recursive https://github.com/Microsoft/cpprestsdk.git casablanca`

Still doesn't work.

**Comment by echotor** [comment] 2017-11-14 07:24
Do you solve this problem? I meet the same problem as you.

**Comment by echotor** [comment] 2017-11-14 07:52
After checking the log and output messages, I find this:
```
CMake Error at src/CMakeLists.txt:14 (list):
  list does not recognize sub-command FILTER
```
I disable this line in src/CMakeLists.txt:14. And cmake build is complete.

**Comment by echotor** [comment] 2017-11-14 07:53
Is this a bug for Ubuntu?

**Comment by ras0219-msft** [comment] 2017-11-14 07:57
Looks like a duplicate of #603. The resolution to that issue should also solve this. Thank you for reporting!

**Closed by ras0219-msft** 2017-11-14 07:57 UTC
