### ISSUE TITLE
this Json is way more complicated, I have no idea how do I build this Json with cpprestsdk?

### ISSUE THREAD

**Issue by abcdef123ghi** [microsoft/cpprestsdk#1589] opened 2021-03-09 02:11 UTC
"input": {
		"druginfo": {
			"acct_used_flag": "1",
			"dise_codg": ""
		}
}

**Comment by barcharcraz** [comment] 2021-03-11 21:07
Closing this as not a bug, if you can provide more information about the problem you're encountering you can reopen the issue.

**Closed by barcharcraz** 2021-03-11 21:07 UTC

**Comment by abcdef123ghi** [comment] 2021-03-18 21:52
> Closing this as not a bug, if you can provide more information about the problem you're encountering you can reopen the issue.

Sorry for any cause inconvenience

**Comment by abcdef123ghi** [comment] 2021-03-18 21:53
Btw I have resolved the problem
