### ISSUE TITLE
SSL error: WINHTTP_CALLBACK_STATUS_FLAG_CERT_REV_FAILED failed to check revocation status. 

### ISSUE THREAD

**Issue by sinall** [Microsoft/cpprestsdk#808] opened 2018-07-15 17:44 UTC
It happens when using cpprestsdk-2.10.2 http_client to access a https website on Windows10.

How to fix it?

**Comment by sinall** [comment] 2018-07-16 04:15
#664

**Comment by BillyONeal** [comment] 2018-08-03 22:17
Closing as a dupe of #664

**Closed by BillyONeal** 2018-08-03 22:17 UTC

**Comment by brennanmh** [comment] 2019-03-22 17:53
This question doesn't seem like a dupe of https://github.com/Microsoft/cpprestsdk/issues/664

#664 is about disabling checking, not how to FIX the problem.
