### ISSUE TITLE
Termination when deleting websocket callback client

### ISSUE THREAD

**Issue by Bobface** [Microsoft/cpprestsdk#701] opened 2018-02-16 21:29 UTC
From time to time when I `delete` an `websocket_callback_client` I get SIGABRT because a thread in websocket_callback_client (`m_thread` in `wspp_callback_client` to be specific) gets deleted by `websocket_callback_client`'s destructor while it is joinable (not finished). I always call `close().get()` on the client before deleting it. Also, the `delete` and `close` are done by an independent thread - not inside a close/message-handler. 

Any ideas how this can happen?

**Comment by whoan** [comment] 2019-03-29 14:23
Did you happen to test if the problem is solved in [v2.10.12](https://github.com/Microsoft/cpprestsdk/releases/tag/v2.10.12) @Bobface ?

**Comment by Bobface** [comment] 2019-03-29 17:53
Sorry I have switched to Boost.Beast since this bug

**Comment by whoan** [comment] 2019-03-29 19:28
I think this issue should be closed in that case

**Closed** 2019-03-30 14:28 UTC
